services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiktok-signature:2.0.0
    environment:
      PORT: 8080
    ports:
      - 8080:8080
    restart: unless-stopped